### ISSUE TITLE
Confusing sentence in Sec.2.2.1 between Def.2.6 and Def.2.7

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#12]
In 2nd paragraph after Def.2.6, after the definition of sub-graph for delg, it is said:
"Conversely, in property graphs, nodes can often be defined without edges." I don't understand why it is said "conversely". The definition of sub-graph for property graphs is defined analogously to the one for delg. The sentence is not really informative and somewhat confusing.

**Comment by Antoine-Zimmermann** [comment]
The "conversely" seems to be opposing this sentence to what is said in the footnote. Maybe this sentence should be part of the footnote.

**Comment by aidhog** [comment]
Agreed, and implemented suggestion in HTML, PHP and LaTeX, adding the sentence to the footnote.
