### ISSUE TITLE
Missing comma in green box of Sec.5.2.1

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#13]
At [line 211 of `05-inductive.php`](https://github.com/Knowledge-Graphs-Book/HTML-Book/blob/32b6da7053c322db5882fdd7bef4a7d6e4895ecb/chapters/05-inductive.php#L211), it is written:

> We denote these as <span style="white-space:nowrap;">\(\mathbf{v}\), \(\mathbf{V}\), \(\mathcal{V}\), \(\mathbf{w}\), \(\mathbf{W}\) \(\mathcal{W}\)</span>

There is a missing comma between `\(\mathbf{W}\)` and `\(\mathcal{W}\)`.

**Comment by aidhog** [comment]
Fixed in HTML, PHP and LaTeX.
