### ISSUE TITLE
Linked PDF version no longer available

### ISSUE THREAD

**Issue by grexe** [Knowledge-Graphs-Book/HTML-Book#14]
In the section "Access options" on the main page, there is a reference to a downloadable PDF version at the publisher's web site at [Morgan & Claypool](http://www.morganclaypoolpublishers.com/catalog_Orig/product_info.php?products_id=1683).
When following the link, the web site says "product not found".

**Comment by Antoine-Zimmermann** [comment]
The reason for this is that Morgan & Claypool sold the rights of the series _Synthesis Lectures on Data, Semantics, and Knowledge_ to Springer. If you use the DOI link (https://doi.org/10.2200/S01125ED1V01Y202109DSK022), you get to the Springer page where you can buy the book. Apart from the book cover, the book is identical to the M&C version. Note that the authors were not informed of this change, so thanks for raising this issue.

**Comment by aidhog** [comment]
Thanks for the feedback @grexe. As @Antoine-Zimmermann mentions, we were not informed of this change. I have updated the HTML version to reflect that the book is now published with Springer and fix the links (now we use the DOI, which appears more stable than the publisher of the book).
