### ISSUE TITLE
Section 2.1.2: Heterogeneous graph only support a one-to-one between nodes and their types?

### ISSUE THREAD

**Issue by krisnadhi** [Knowledge-Graphs-Book/HTML-Book#16]
Hi, 

In the text in section 2.1.2, it is stated that "Conversely, such graphs typically only support a one-to-one relation between nodes and types". I suppose this should have been "many-to-one" relation, because multiple nodes may belong to the same type as illustrated in Figure 2.2(b)?

**Comment by Antoine-Zimmermann** [comment]
You're right. The idea was to say that "one node -> one type", that is, one node is mapped to only one type. But of course, the same type can be used for many nodes.

**Comment by aidhog** [comment]
Fixed in the PHP, HTML and LaTeX as suggested (one-to-one -> many-to-one). Thanks for the comment @krisnadhi !
