### ISSUE TITLE
typo in Appendix: "as Sowa [1979]a later wrote"

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#18]
In Section A.1, there is an extra "a" after the reference to Sowa [1979] that should not be there.

**Comment by aidhog** [comment]
Fixed in HTML and PHP. Not an issue in the LaTeX. https://github.com/Knowledge-Graphs-Book/HTML-Book/commit/16e6bb49ab5058b434fd314296455c3beb540c77
