### ISSUE TITLE
Extra parenthesis in 1st paragraph of Section 2.2.2

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#20]
In Sec.2.2.2, it's written "left-join (⟕), aka optional)".There is an extra closing parenthesis after the left-join symbol that shouldn't be there.

**Comment by aidhog** [comment]
Seems like this was partially fixed in HTML in one place, not the other. Fixed (along with a later instance) in both HTML & PHP. Not an issue in LaTeX.
