### ISSUE TITLE
Missing closing parenthesis in 1st paragraph of Chapter 9

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#27]
The first sentence has an oppening parenthesis that never closes:

> While it may not always be desirable to publish knowledge graphs (for example, those that offer a competitive advantage to a company [[Noy et al., 2019](https://www.emse.fr/~zimmermann/LivreGdC/Livre-HTML/book.php#ref-NoyGJNPT19)], it may be desirable ...

The closing parenthesis should be immediately after the reference.

**Comment by aidhog** [comment]
Fixed in HTML and PHP. Not an issue in the LaTeX.
