### ISSUE TITLE
Homogenise punctuation in sub-bullet lists of Sec.9.1.1

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#29]
Sub-goals A1.1 and A1.2 are followed by a colon, while sub-goals R1.1, R1.2, and R1.3 are followed by a point. I suggest using colons everywhere.

**Comment by aidhog** [comment]
Changed to colons everywhere.

**Comment by aidhog** [comment]
Also fixed in PHP. https://github.com/Knowledge-Graphs-Book/HTML-Book/commit/050e162e3853be8e795eaa475431bd17e3d235cc
