### ISSUE TITLE
misplaced full stop before closing parenthesis in Sec. 8.1

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#30]
The paragraph at the beginning of Sec.8.1 ends with:

> will be discussed later in Section [9.1](https://www.emse.fr/~zimmermann/LivreGdC/Livre-HTML/book.php#ssec-principles).)

Full stop must be after the closing parenthesis.

**Comment by Antoine-Zimmermann** [comment]
The parenthesis could be simply removed.

**Comment by aidhog** [comment]
Removed the parenthesis. (I think it's a matter of style more than a typo. If what's inside are full sentences it makes sense to put the full-stop inside I think. Otherwise it's weird to me to put the last full-stop outside like this).

**Comment by aidhog** [comment]
(Removed from both HTML version and LaTeX of book.)

**Comment by aidhog** [comment]
Also fixed in PHP https://github.com/Knowledge-Graphs-Book/HTML-Book/commit/13c252f876bcc7b4a70e09508bc933372da1fae6
