### ISSUE TITLE
Missing closing parenthesis in Section 7.3.2

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#33]
The missing parenthesis is after "3.1.2":

> ...expressions [[Thornton et al., 2019](https://www.emse.fr/~zimmermann/LivreGdC/Livre-HTML/book.php#ref-ThorntonSSGMPW19)] (see Section [3.1.2](https://www.emse.fr/~zimmermann/LivreGdC/Livre-HTML/book.php#sssec-validating-schema). We may, for example,...

**Comment by aidhog** [comment]
Only appears in HTML version (fixed).
