### ISSUE TITLE
Name "Joan Dubois" for a claimant from France

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#35]
The first name "Joan" is extremely rare in France, at least as a given name from birth. Since the beginning of the XXth century, it has been given 118 times in total in France, with a maximum of 9 times in 1982 and in 1984. Perhaps it is a confusion with the super common name "Jean" (equivalent of "John"), which although it is given less and less in France, is still considered the most common first name with more than a million people bearing it.

I suggest we change "Joan" into "Jean".

**Comment by aidhog** [comment]
Probably a mistake from _Jeanne d'Arc_, who is known as _Joan of Arc_ in English.

Changed Joan to Jeanne (given that the other two are men) in HTML, PHP and LaTeX. 
(Not sure how popular the name Jeanne is but I think it shouldn't look out of place?)

**Comment by Antoine-Zimmermann** [comment]
Yes, "Jeanne" is fine. Much less popular than "Jean", but still hugely more popular than "Joan".
