### ISSUE TITLE
Missing name in bibliography

### ISSUE THREAD

**Issue by agnieszkalawrynowicz** [Knowledge-Graphs-Book/HTML-Book#4]
Congratulations on the great book!  

I have spotted a mistake in the bibliography:
1)
In chapter 6.5.1 Ontology engineering there should be:
Keet, 2016 Keet and Lawrynowicz, 2016

2) 
In Bibliography:
There is: 
C. Maria Keet. 2016. Test-driven development of ontologies. In The Semantic Web. Latest Advances and New Domains - 13th International Conference, ESWC 2016, Heraklion, Crete, Greece, May 29 - June 2, 2016, Proceedings, Harald Sack, Eva Blomqvist, Mathieu d'Aquin, Chiara Ghidini, Simone Paolo Ponzetto, and Christoph Lange (Eds.). Lecture Notes in Computer Science, vol. 9678. Springer, 642–657.

There should be:
C. Maria Keet, and Agnieszka Lawrynowicz. 2016. Test-driven development of ontologies. In The Semantic Web. Latest Advances and New Domains - 13th International Conference, ESWC 2016, Heraklion, Crete, Greece, May 29 - June 2, 2016, Proceedings, Harald Sack, Eva Blomqvist, Mathieu d'Aquin, Chiara Ghidini, Simone Paolo Ponzetto, and Christoph Lange (Eds.). Lecture Notes in Computer Science, vol. 9678. Springer, 642–657.

Thank you in advance.
Kind Regards and cheers,
Agnieszka

**Comment by Antoine-Zimmermann** [comment]
Thanks for the feedback. In fact, the BibTeX file that is used for the HTML book contains your name (see the BibTeX entry that appears when you hover your mouse over the reference at https://kgbook.org/#ref-keet2016test) but it seems that the PHP library I'm using for this has a problem with the character "\L" (Ł) in your name, so the name is completely skipped. I can fix this.

**Comment by agnieszkalawrynowicz** [comment]
Great! 
Btw, I am used to various issues regarding the processing of the first letter of my name (e.g., question mark instead the letter or missing letter at some systems etc.):-)     

Thank you a million Antoine!:-)

Kind regards and cheers,
Agnieszka
