### ISSUE TITLE
BibTeX code no longer syntax-highlighted

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#59]
The BibTeX code is no longer syntax-highlighted. The reason is that the JS responsible for it came from a file somewhere else on the Web and is no longer available. We must replace line 26 of book.php:

    <script src="https://saswatpadhi.github.io/prismjs-bibtex/prism-bibtex.min.js"></script>

with:

	<script src="https://cdn.jsdelivr.net/npm/prismjs-bibtex@2.1.0/prism-bibtex.js"
	        integrity="sha256-A5GMUmGHpY8mVpfcaRLQFeHtmdjZLumKBOMpf81FXX0="
	        crossorigin="anonymous" referrerpolicy="no-referrer">
	</script>

I opened pull request #58 for this.

**Comment by miselico** [comment]
Save a few bytes and use
***@***.***/prism-bibtex.min.js
instead?

**Comment by Antoine-Zimmermann** [comment]
I updated the files and merged, with a slight hickup as I needed to change the integrity checksum too. See #60 .
