### ISSUE TITLE
A typo in a sentence in Chapter 5.2 (or my own misunderstanding)

### ISSUE THREAD

**Issue by Hyunha** [Knowledge-Graphs-Book/HTML-Book#63]
In the first sentence of the third paragraph of Chapter 5.2 (Knowledge Graph Embeddings),

https://github.com/Knowledge-Graphs-Book/HTML-Book/blob/249d51d730397d628771e4da26e188f629b32e1a/chapters/05-inductive.php#L137

> The main goal of knowledge graph embedding techniques is to create a dense representation of the graph (i.e., embed the graph) in a continuous, low-dimensional vector space that can then be used for machine learning tasks. The dimensionality _d_ of the embedding is fixed and usually low (often, e.g., 50 ≥ d ≥ 1000).

I think 50 ≥ d ≥ 1000 should be 50 ≤ d ≤ 1000.

or am I missing something?

**Comment by miselico** [comment]
Thank you for pointing this out. 
I fixed it in #64 , the preview is hosted at https://knowledge-graphs-book.github.io/HTML-Book-staging/fixing-issue-63/ @Hyunha could you check whether this resolves this issue?
