### ISSUE TITLE
"In the rest of the paper" Sec.2.1.5

### ISSUE THREAD

**Issue by Antoine-Zimmermann** [Knowledge-Graphs-Book/HTML-Book#8]
In Section 2.1.5, it is written "In the rest of the paper, we prefer discussing ..." which is a residue of the previous version published as a "research paper" (i.e., article) instead of a book.
Suggestion: change this to "In the rest of the book, ..."

**Comment by aidhog** [comment]
Fixed in HTML, PHP and LaTeX.
